### ISSUE TITLE
improve / verify service management

### ISSUE THREAD

**Issue by mmetc** [crowdsecurity/pfSense-pkg-crowdsec#1]
What's the proper way to start/stop crowdsec services?

We are currently using "service crowdsec/crowdsec_firewall enable/disable/start/stop" which is vanilla freebsd and seems to work but

 - the files "crowdsec", "crowdsec_firewall" and "pfsense_crowdsec" should not be part of the package
 - /etc/rc.conf says "this file does nothing"
 - https://docs.netgate.com/pfsense/en/latest/development/boot-commands.html

**Comment by julienloizelet** [comment]
Note:
when we run "service crowdsec start" while saving the settings, it does not work as expected: 
there is a syslog message : The command 'service crowdsec start' returned exit code '1', the output was 'crowdsec already running?
Thus, service is not restarted with the modified yaml files.

**Comment by julienloizelet** [comment]
Related: https://github.com/crowdsecurity/pfSense-pkg-crowdsec/issues/43

**Comment by mmetc** [comment]
should be fixed in https://github.com/crowdsecurity/pfSense-pkg-crowdsec/pull/52
