### ISSUE TITLE
Address family for host not supported

### ISSUE THREAD

**Issue by comfuzio** [crowdsecurity/pfSense-pkg-crowdsec#100]
Hi, I had to format my mini-pc/router and reinstall pfsense CE.
I saw the new installer and I thought of giving a try, this is the command output from the terminal:

fetch https://raw.githubusercontent.com/crowdsecurity/pfSense-pkg-crowdsec/refs/heads/main/install-crowdsec.sh
fetch: https://raw.githubusercontent.com/crowdsecurity/pfSense-pkg-crowdsec/refs/heads/main/install-crowdsec.sh: Address family for host not supported

Any idea on how to resolve that?

**Comment by mmetc** [comment]
Hi,

if you can't download it with fetch/wget/curl (I guess it's an ipv6/dns thing), you can just copy-paste the content to a new file.

**Comment by comfuzio** [comment]
While I have tried like 20 times before I have opened the issue here, on the 21st time with the command above it worked.
No words.
Thanks for your kind reply
