### ISSUE TITLE
cron job

### ISSUE THREAD

**Issue by mmetc** [crowdsecurity/pfSense-pkg-crowdsec#11]
see opnsense plugin, it should update the hub etc.
are there other pfsense packages with cron files?

**Comment by julienloizelet** [comment]
FYI, I did not find any plugin with a cron.
 
The content of the `/etc/crontab` file suggest to create files in /etc/cron.d/. (or use the cron package)

I guess it could be done like for the crowdsec package: https://github.com/pfsense/FreeBSD-ports/blob/devel/security/crowdsec/files/crowdsec.cron.in.

Finally, I saw it could be done programmatically using the `configure_cron` method: https://github.com/pfsense/pfsense/blob/master/src/etc/inc/services.inc#L3363
We would need to add a `cron/item` node in the `config.xml` and call this method.

**Comment by mmetc** [comment]
we don't need a custom cron, we can use the existing one *but* it must not call "service crowdsec reload" if it's not already running.
