### ISSUE TITLE
ramdisk in /var/ and database in /var/db/

### ISSUE THREAD

**Issue by mmetc** [crowdsecurity/pfSense-pkg-crowdsec#21]
If pfsense is set up to use a RAM disk for /var, the LAPI cannot be used because its database and geoip tables would be lost at every reboot. opnsense had the same option but they switched it to /var/log in recent releases.

We can:

 - warn the user in the install docs, to disable ram disk and reboot (done)
 - provide a checkbox to install the database in /conf/ or /root/, this can set data_dir before running crowdsec for the first time. This is pragmatic but doesn't fit with the rest of the options, because it cannot be changed later.
 - detect if RAM disk is enabled in the configuration and warn the user in the UI -- does not solve the issue but it's a safeguard
 - always install the db in /root/ or /conf/ instead of /var/db/. meh.

if option 1 is enough, we can close this. Maybe 1+3 ?

**Comment by julienloizelet** [comment]
Point 3 done in https://github.com/crowdsecurity/pfSense-pkg-crowdsec/pull/26
