### ISSUE TITLE
install default collections

### ISSUE THREAD

**Issue by mmetc** [crowdsecurity/pfSense-pkg-crowdsec#23]
As soon as possible after the package is installed (possibly before running crowdsec) we need to install the pfsense collection, which is currently in a branch of the hub.
So the procedure is:

 - if the file /usr/local/etc/crowdsec/collections/pfsense.yaml already exists: ignore all the following steps
 - set "cscli.hub_branch: pfsense-gui" in config.yaml
 - cscli hub update
 - cscli collections install crowdsecurity/pfsense
 - service crowdsec reload

This can be executed, for example, when the settings form is saved and we ensured that crowdsec is running

**Comment by julienloizelet** [comment]
Should be done here: https://github.com/crowdsecurity/pfSense-pkg-crowdsec/pull/26
