### ISSUE TITLE
settings form feeback

### ISSUE THREAD

**Issue by mmetc** [crowdsecurity/pfSense-pkg-crowdsec#24]
We should have a feedback from the settings form, even if there are no errors. Like the message "The changes have been applied successfully" in guiconfig.inc

Once we have a feedback, we can use it to communicate a few more things

Example: IF when the settings form is saved, we just started crowdsec, we can

 - wait a couple of seconds
 - if crowdsec is not running, feedback to the user and ask to check the logs
 - if crowdsec is running, and pfsense.yaml is missing, proceed to install it and feedback to the user saying "installed collection crowdsecurity/pfsense", or just the command's output

**Comment by julienloizelet** [comment]
Should be done here: https://github.com/crowdsecurity/pfSense-pkg-crowdsec/pull/26
