### ISSUE TITLE
actions at install time

### ISSUE THREAD

**Issue by mmetc** [crowdsecurity/pfSense-pkg-crowdsec#36]
at install time, not resync:

$candidate_log_dir = '/var/log/crowdsec/'                                                                                                                 
$candidate_log_max_size = 999999                                                                                                                           
$candidate_db_wal = true

disable bouncer metrics (prometheus.enabled = false)

**Comment by mmetc** [comment]
we can remove the bouncer metrics port, I don't think anybody is using it and they can reactivate with manual edit

**Comment by julienloizelet** [comment]
> we can remove the bouncer metrics port

Done with https://github.com/crowdsecurity/pfSense-pkg-crowdsec/pull/48
