### ISSUE TITLE
Syntax error on crowdsec.inc

### ISSUE THREAD

**Issue by ToeiRei** [crowdsecurity/pfSense-pkg-crowdsec#55]
Syslog says

```
/rc.filter_configure_sync: There was an error while parsing the package filter rules for /usr/local/pkg/crowdsec.inc.
/rc.filter_configure_sync: The command '/sbin/pfctl -nf /tmp/rules.test.packages' returned exit code '1', the output was '/tmp/rules.test.packages:72: syntax error'

```

... on a fresh install of the package - haven't had crowdsec on it before.

**Comment by mmetc** [comment]
Hi, thanks for the report!

I have not seen this before. Since the file /tmp/rules.test.packages is dynamically generated depending on the firewall configuration, we should have a look at what's in line 72.

> ... on a fresh install of the package - haven't had crowdsec on it before.

Yes, the bouncer on freebsd is using a packet filter backend instead of iptables/nftables so you have not run this code yet.

**Comment by ToeiRei** [comment]
wouldn't it make sense to allow users to use the aliases in their own rules as well? It would allow us to be a bit more flexible

**Comment by mmetc** [comment]
It should just work, did you try? That's why we have the option of disabling the rules, to replace them with your own.

**Comment by ToeiRei** [comment]
they seem to be filled only when the bouncer is checked

**Comment by andrasg** [comment]
I am seeing this error too.

```
/rc.filter_configure_sync: The command '/sbin/pfctl -nf /tmp/rules.test.packages' returned exit code '1', the output was '/tmp/rules.test.packages:35: syntax error'
```

Line 35 in `rules.test.packages`:
```
block drop inlog  quick  inet6 from <crowdsec6_blacklists> to any label "CrowdSec IPv6"
```
Probably missing a space between "in" and "log" ?

**Comment by andrasg** [comment]
Disabling the IPv6 blocklist rule in crowdsec pfsense settings gets rid of the error.

**Comment by mmetc** [comment]
or just disable the log. Fixed in https://github.com/crowdsecurity/pfSense-pkg-crowdsec/pull/60 , thanks!
