### ISSUE TITLE
security engine got stopped, no bouncer checkin on central api

### ISSUE THREAD

**Issue by celevra** [crowdsecurity/pfSense-pkg-crowdsec#58]
hi,

i'm testing the pfsense plugin.
Thank you for your work.
Today my monitoring told me that a bouncer didn't checked in for a few days.
It is the pfsense running the new plugin.
after check it seems like the security engine stopped (seen on the status screen). 
But after pressing save again on the settings screen there is again a green checkmark on both but no new api pull from the bouncer.

what should i provide that you can dig deeper?

regards

**Comment by mmetc** [comment]
Hi, is it possible to see /var/log/crowdsec/crowdsec.log, a few lines before you restarted it?

Thanks!

**Comment by celevra** [comment]
hm looks strange, 

```
time="11-09-2023 08:48:40" level=info msg="Force add watch on /var/log" type=file
time="11-09-2023 08:48:40" level=info msg="Adding file /var/log/filter.log to datasources" type=file
time="11-09-2023 08:48:40" level=info msg="Starting processing data"
time="11-09-2023 08:49:10" level=fatal msg="starting outputs error : authenticate watcher (hq): Post \"http://xxx:8181/v1/watchers/login\": performing jwt auth: dial tcp xxx.xxx.xxx.xxx:8181: i/o timeout"
time="16-09-2023 08:00:19" level=warning msg="crowdsec local API is disabled because 'enable' is set to false"
time="16-09-2023 08:00:19" level=info msg="Enabled feature flags: disable_http_retry_backoff"
```

got the same message yesterday an security engine got an red X
the IP it tries to connect to is only reachable if the VPN of the Firewall is up and running, 
Could be that to that time it was offline

**Comment by mmetc** [comment]
Hi,

can you try this new version? You need to install all the four packages, go check the settings and save.

https://github.com/crowdsecurity/pfSense-pkg-crowdsec/releases/tag/v0.0.4

Thanks!

**Comment by celevra** [comment]
firewall bouncer is fixed
we will see if engine gets stopped over the weekend, thanks for your work
