### ISSUE TITLE
bouncer not picking up remote API?

### ISSUE THREAD

**Issue by andrasg** [crowdsecurity/pfSense-pkg-crowdsec#59]
I have disabled local API and after that I am seeing errors in `crowdsec-firewall-bouncer.log` every 10 seconds:

```
time="16-09-2023 18:16:46" level=error msg="auth-api: auth with api key failed return nil response, error: dial tcp 127.0.0.1:8080: connect: connection refused"
time="16-09-2023 18:16:46" level=error msg="failed to connect to LAPI, retrying in 10s: Get \"http://127.0.0.1:8080/v1/decisions/stream?startup=true\": dial tcp 127.0.0.1:8080: connect: connection refused"
```

Looks like the API IP is still read from the LAPI section in config. If I enable LAPI, change the LAPI IP to the remote IP, then disable LAPI, it seems to work ok.

**Comment by mmetc** [comment]
Hi,

there is a new version at https://github.com/crowdsecurity/pfSense-pkg-crowdsec/releases/tag/v0.0.4

it should fix this problem

Thanks again!
