### ISSUE TITLE
Unresolvable source alias 'crowdsec_blacklists' for rule 'crowdsec generated blocklist ip4 from crowdsec plugin'

### ISSUE THREAD

**Issue by europacafe** [crowdsecurity/pfSense-pkg-crowdsec#72]
After upgrading from 0.0.4 to 0.1, there are two messages notified by pfSense:
```
Unresolvable source alias 'crowdsec_blacklists' for rule 'crowdsec generated blocklist ip4 from crowdsec plugin' @ 2023-11-07 07:44:19
Unresolvable source alias 'crowdsec6_blacklists' for rule 'crowdsec generated blocklist ip6 from crowdsec plugin' @ 2023-11-07 07:44:20
```
crowdsec_blacklists and crowdsec6_blacklists are two aliases auto generated by crowdsec. In v.0.0.4, I use these two aliases to create two block rules in Firewall/Rules/WAN, it never has this error message and the firewall log files did show that the two blocking rules worked. I'm not sure what has been changed in the new version. Checking the firewall logs, the rules are no longer blocking anything!

**Comment by europacafe** [comment]
update: those firewall rules are blocking now. Crowdsec on pfSense may take a bit time to get all the blacklist downloaded?
My question is do I really need to create these two blocking rules (using crowdsec_blacklist & crowdsec6_blacklist aliases) manually on Firewall/Rules/WAN or blocking IP is already working behind the scene?

**Comment by mmetc** [comment]
Hi,

the alias is not hidden from the UI and you should be able to see it in the alias page. I don't know why it was not present at first. Nothing has changed from the previous version there.

You don't need to create any rule manually, just enable them in the settings. They are automatically created (and hidden from view). Let me know how the documentation can be improved if it's not clear enough.

**Comment by europacafe** [comment]
I didn’t mean the aliases were hidden. They are right there after the installation. I was just not sure I need to create firewall rules to make use of it or they are already used to block those IPs behind the scene. So from what you said, I don’t need to manually create extra firewall rules.
Sorry English is not my first language and it may have confused you.

**Comment by mmetc** [comment]
> I didn’t mean the aliases were hidden. They are right there after the installation. I was just not sure I need to create firewall rules to make use of them or they are already used to block those IPs behind the scene.

Oh yes I see. Behind the scenes because as far as I know you can't see the automatically created rules (while on opnsense for example, they are shown and clearly marked).
