### ISSUE TITLE
Can't register my crowdsec on unraid to use LAPI on my pfSense

### ISSUE THREAD

**Issue by europacafe** [crowdsecurity/pfSense-pkg-crowdsec#73]
I want my crowdsec on my unraid to use LAPI on my pfSense.
I issued this command on crowdsec console (run as container on unraid):
`cscli lapi register -u 1xx.xx.xx.x`
where 1xx.xx.xx.x is my pfSense ip running crowdsec full stack
As my pfSense always redirects to https:, registration can't pass through, and return this message:
`FATA[07-11-2023 14:23:11] api client register: api register (http://1xx.xx.xx.x/): Post "https://1xx.xx.xx.x.:10443/v1/watchers": tls: failed to verify certificate: x509: cannot validate certificate for 1xx.xx.xx.x because it doesn't contain any IP SANs`

What should I do?

**Comment by LaurenceJJones** [comment]
> As my pfSense always redirects to https:

So you have exposed and installed a certificate on the CrowdSec port?

**Comment by europacafe** [comment]
It is the self-signed coming pre-installed with pfSense installation.

**Comment by LaurenceJJones** [comment]
> It is the self-signed coming pre-installed with pfSense installation.

Then you will need to set the `insecure_verify: true` within the configurations as it not signed by a CA

https://docs.crowdsec.net/docs/next/configuration/crowdsec_configuration#insecure_skip_verify

**Comment by mmetc** [comment]
TLS is something that should be configured by the plugin itself, but we didn't include it in the first version. The PHP file crowdsec.inc is hardcoding "http" in the configuration, for both lapi and bouncer, so you may want to change it.

**Comment by europacafe** [comment]
It is my bad. I have to specify the crowdsec LAPI port 8080 too, i.e,
`cscli lapi register -u 1xx.xx.xx.x:8080`
Thank you
