### ISSUE TITLE
Packages for aarch64

### ISSUE THREAD

**Issue by peterg10** [crowdsecurity/pfSense-pkg-crowdsec#76]
The release packages are for amd64 only, would it be possible to get them for ARM (Netgate 2100)?

```
[23.09-RELEASE][admin@xxxxxxxxxxxxx]/:` pkg add abseil-20230125.3.pkg
Installing abseil-20230125.3...
pkg: wrong architecture: FreeBSD:14:amd64 instead of FreeBSD:14:aarch64

Failed to install the following 1 package(s): abseil-20230125.3.pkg
```

**Comment by mmetc** [comment]
Hi @peterg10 

I don't have a build environment for arm, but you can try installing the FreeBSD 14 versions from freshports.org, there should be everything except the pfSense-pkg-crowdsec package which does not have binaries.

In the meanwhile I'll see if I can set up an ARM VM for the builds, it's a good idea anyway. I was not aware of the availability of pfSense on that architecture

**Comment by mmetc** [comment]
Hi @peterg10 ,

you can find a set of aarch64 binaries in the release assets, "aarch64-packages.tar"

Let me know if they work for you

**Comment by peterg10** [comment]
So far, so good. The packages installed without error on a Netgate SG2100 and the menu entries are present under Services and Diagnostics. Reading the docs and configuring it now.

Thanks for the packages!!
