### ISSUE TITLE
Upgrading needs to delete /usr/local/etc/crowdsec folder before installing a new version?

### ISSUE THREAD

**Issue by europacafe** [crowdsecurity/pfSense-pkg-crowdsec#88]
I'm going to upgrade my Crowdsec from 0.1.2 to 0.1.3 version, I know at least I have to remove the 5 old packages first before installing the latest ones. In the past upgrades, I delete it and re-setup again after installing a new version.
My question is do I have to delete the old config folder (/usr/local/etc/crowdsec/) before I install the newer packages? I do not want to if not necessary because I'll lose the old setups.

Thanks

**Comment by Infamousbugg** [comment]
I don't think you need to remove the config dirs. I just installed Crowdsec last week and updated to 0.1.3 yesterday without issue. I installed the new packages without removing the old ones first. When I do a pkg show I only see the new packages, so I'm not sure removing the old ones is needed.

**Comment by europacafe** [comment]
Thanks. Just upgraded it and every setup is still there. I did the remove old version part, though. I'll try not to do it for the next version.
Thanks again.
