### ISSUE TITLE
Machine "pfsense" removed after reboot

### ISSUE THREAD

**Issue by pvillmann** [crowdsecurity/pfSense-pkg-crowdsec#90]
Hi,

i'am using crowdsec on my pfsense as central LAPI. (6 Log processors for different applications).

The problem is, after each reboot of pfsense the crowdsec service starts not automatically because the local "machine" cannot connect to "local lapi".
On the Machine list there is no "pfsense" machine listed.

If I run after each startup the command "cscli machine add pfsense -a --force" and start then the crowdsec service manually, everthing works fine.

Any ideas?

Thanks a lot :)

**Comment by mmetc** [comment]
For this issue, I think the reason is you have /var in a ram disk. If that's not the case, please try the latest version

https://github.com/crowdsecurity/pfSense-pkg-crowdsec/releases/tag/v0.1.4-1.6.3_2

**Comment by pvillmann** [comment]
Hi... sorry i forgot to give feeback here... After i have updated to 1.6.2 and register my local pfsense instance again to 127.0.0.1 everything works fine... 
So at the, for me, issue can be closed.

**Comment by p-schneider** [comment]
For me that issue still persists with the latest v0.1.4-1.6.3_2 (having local lapi host set to my LAN IP instead of 127.0.0.1).
But the workaround I've been using for a long time also still works, so I'll keep doing that for now.

**Comment by mmetc** [comment]
If you do so, check the bouncer logs for any surprise. It's also stored in the local db and if it can't connect, there is no protection. If you have /var in ram see if you can change that
