### ISSUE TITLE
Installing latest test version failing on 24.08

### ISSUE THREAD

**Issue by yuryk1** [crowdsecurity/pfSense-pkg-crowdsec#96]
Installation getting stuck on pfSense-pkg-crowdsec install. Tried script installation and manual - same issue.

```
Installing pfSense-pkg-crowdsec-0.1.4...
Newer FreeBSD version for package pfSense-pkg-crowdsec:
To ignore this error set IGNORE_OSVERSION=yes
- package: 1500023
- running kernel: 1500019
Ignore the mismatch and continue? [y/N]: y
package pfSense-pkg-crowdsec is already installed, forced install
Extracting pfSense-pkg-crowdsec-0.1.4: 100%
Saving updated package information...
overwrite!
Loading package configuration... done.
Configuring package components...
Loading package instructions...
Custom commands...
Executing custom_php_install_command()...done.
Executing custom_php_resync_config_command()..
```

**Comment by yuryk1** [comment]
script works fine with release version (no version tag)

**Comment by mmetc** [comment]
thanks for testing!

Two questions

 - pfsense community on amd/intel, right?
 - new install or upgrade?
 
To better reproduce the issue, it would be great if you could run "cscli support dump" and mail the resulting file to support@crowdsec.net, so that I can have a look at the logs

**Comment by mmetc** [comment]
There was an issue in some cases with 1.6.2 when it came to stopping the service. I though the script would take care of that.

You can try to run the installer (with --release v1.0.4-1.6.3_1) again after manually terminating the process and its manager

```
# kill -9 `ps xw | grep crowdsec | grep -v grep | awk '{print $1'}`
```

**Comment by mmetc** [comment]
A new version which fixes the reason you had to terminate the process. But you should not "enable" the service, as it's managed by pfsense.

https://github.com/crowdsecurity/pfSense-pkg-crowdsec/releases/tag/v0.1.4-1.6.3_2
