### ISSUE TITLE
Suddenly the LAPI is down

### ISSUE THREAD

**Issue by europacafe** [crowdsecurity/pfSense-pkg-crowdsec#98]
Crowdsec 1.6.3

I've upgraded from 1.6.2 for a few days ago and suddenly this morning I can't query all the LAPI metrics
![image](https://github.com/user-attachments/assets/c5c26fed-fc40-4d3d-8c05-1d61ed4d7c3a)
![image](https://github.com/user-attachments/assets/791dc1a8-d78a-4b1c-9645-dc4eb03e416d)
crowdsec log on pfSense
![image](https://github.com/user-attachments/assets/2ddcc08c-ec95-4080-a76e-b1fcd128225e)

The crowdsec pfsense GUIs are still there, but it can't list pfsense machine.
I also tried cscli capi register again with success (it generated new CAPI credentials).
I also tried re-installing the crowdsec module. No help.

I've never encountered this problem since the pre-1.0 version. Every time there were new versions, I upgraded them every time.
Need help....thanks.

**Comment by mmetc** [comment]
Hi, can you please run "cscli support dump" (with or without an instance running, doesn't matter) and send the output to support@crowdsec.net?

Don't bother with registering to capi, this is a local issue.

I should upload a new version today, and let you know.

Thanks

**Comment by europacafe** [comment]
Thanks. Will do.
I'm not sure this is relevant. Pfsense DNS Resolver or unbound module also crashed after it has started for a short time.

**Comment by mmetc** [comment]
Thanks. No I don't think it's relevant.

We released a new version here, you can try it (best after sending us the crowdsec-support.zip)

https://github.com/crowdsecurity/pfSense-pkg-crowdsec/releases/tag/v0.1.4-1.6.3_2

I recommend you to use the script to upgrade.

**Comment by europacafe** [comment]
I've upgraded crowdsec from the very early version for every new version until 1.6.2 without any problem. It worked great.
However, 1.63.1 really ruined my pfSense to the point I had to fresh install my pfSense, and re-installed 1.63.1 again and it also corrupted my pfSense till it no longer works. I've now fresh installed my pfSense 2.7.2 again and I'm really afraid to install crowdsec again.

Sorry I did not keep the error log, but it reported something about python error things.

Is it safe to install the latest version?

**Comment by mmetc** [comment]
Hi,

there is no python in the crowdsec packages, plugins or anything related. Crowdsec is written in go and the pfsense plugin is php, javascript and bash.

What do you mean by "ruined" and "no longer works"? Where did you see these errors?

**Comment by europacafe** [comment]
The errors were reported on pfSense gui and I have to click the link to see a bunch of errors. Sorry I didn't capture the error reports.

The main break was that the dns resolver or unbound function on pfSense can't be started.

Could you tell how the new installation script is different from the manual package removal and adding?

**Comment by mmetc** [comment]
I don't think the errors are releated to crowdsec, the only configuration it changes is the firewall tables (IP addresses, so no need to involve dns)

The install script detects the OS version and CPU architecture, connects to github to download the release marked as "latest" - or the one chosen by the user, it then extracts the packages, removes the old ones and installs the new ones after making sure all crowdsec processes were terminated correctly.

**Comment by europacafe** [comment]
Thanks. I may try the script and 1.6.3-2 later.

**Comment by europacafe** [comment]
Just to update.

From the fresh installation of my pfSense, I used the installation script to install crowdsec 1.6.3-2 without problem.

Thank you very much for the great script.
